// <auto-generated />
using CS_EFCore_CodeFirst_KalpeshSoliya.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CS_EFCore_CodeFirst_KalpeshSoliya.Migrations
{
    [DbContext(typeof(ScikeyLabDbContext))]
    [Migration("20210909102146_Migration_First")]
    partial class Migration_First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CS_EFCore_CodeFirst_KalpeshSoliya.Models.Category", b =>
                {
                    b.Property<int>("CategoryRowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CategoryRowId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CS_EFCore_CodeFirst_KalpeshSoliya.Models.Products", b =>
                {
                    b.Property<int>("ProductRowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryRowId")
                        .HasColumnType("int");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ProductRowId");

                    b.HasIndex("CategoryRowId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CS_EFCore_CodeFirst_KalpeshSoliya.Models.Vender", b =>
                {
                    b.Property<int>("VenderRowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("VenderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VenderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("VenderRowId");

                    b.ToTable("Venders");
                });

            modelBuilder.Entity("CS_EFCore_CodeFirst_KalpeshSoliya.Models.VendorProduct", b =>
                {
                    b.Property<int>("VenderProductRowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductRowId")
                        .HasColumnType("int");

                    b.Property<int>("VenderRowId")
                        .HasColumnType("int");

                    b.HasKey("VenderProductRowId");

                    b.HasIndex("ProductRowId");

                    b.HasIndex("VenderRowId");

                    b.ToTable("VendorProduct");
                });

            modelBuilder.Entity("CS_EFCore_CodeFirst_KalpeshSoliya.Models.Products", b =>
                {
                    b.HasOne("CS_EFCore_CodeFirst_KalpeshSoliya.Models.Category", "Categtory")
                        .WithMany("Products")
                        .HasForeignKey("CategoryRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categtory");
                });

            modelBuilder.Entity("CS_EFCore_CodeFirst_KalpeshSoliya.Models.VendorProduct", b =>
                {
                    b.HasOne("CS_EFCore_CodeFirst_KalpeshSoliya.Models.Products", "Product")
                        .WithMany("VendorProducts")
                        .HasForeignKey("ProductRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CS_EFCore_CodeFirst_KalpeshSoliya.Models.Vender", "Vender")
                        .WithMany("VendorProducts")
                        .HasForeignKey("VenderRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Vender");
                });

            modelBuilder.Entity("CS_EFCore_CodeFirst_KalpeshSoliya.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CS_EFCore_CodeFirst_KalpeshSoliya.Models.Products", b =>
                {
                    b.Navigation("VendorProducts");
                });

            modelBuilder.Entity("CS_EFCore_CodeFirst_KalpeshSoliya.Models.Vender", b =>
                {
                    b.Navigation("VendorProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
